"""create initial schema

Revision ID: 8309737e2f1a
Revises: 
Create Date: 2026-08-23 01:03:23.517435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8309737e2f1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('seeded', 'pasted', 'upload')", name='ck_meetings_source_type'),
    sa.CheckConstraint('duration_seconds >= 0', name='ck_meetings_duration_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('ix_meetings_meeting_date', ['meeting_date'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320, collation='NOCASE'), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index('ix_participants_name', ['name'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('sequence_index >= 0', name='ck_action_items_sequence_non_negative'),
    sa.CheckConstraint('timestamp_ms IS NULL OR timestamp_ms >= 0', name='ck_action_items_timestamp_non_negative'),
    sa.ForeignKeyConstraint(['assignee_id'], ['participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'sequence_index', name='uq_action_items_meeting_sequence')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('ix_action_items_assignee_id', ['assignee_id'], unique=False)
        batch_op.create_index('ix_action_items_meeting_id', ['meeting_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_time_ms', sa.Integer(), nullable=False),
    sa.Column('end_time_ms', sa.Integer(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_time_ms IS NULL OR end_time_ms >= start_time_ms', name='ck_chapters_time_order'),
    sa.CheckConstraint('sequence_index >= 0', name='ck_chapters_sequence_non_negative'),
    sa.CheckConstraint('start_time_ms >= 0', name='ck_chapters_start_non_negative'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'sequence_index', name='uq_chapters_meeting_sequence')
    )
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('is_organizer', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meeting_id', 'participant_id')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index('ix_meeting_participants_participant_meeting', ['participant_id', 'meeting_id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.CheckConstraint('sequence_index >= 0', name='ck_topics_sequence_non_negative'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'sequence_index', name='uq_topics_meeting_sequence')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('start_time_ms', sa.Integer(), nullable=False),
    sa.Column('end_time_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time_ms >= start_time_ms', name='ck_transcript_segments_time_order'),
    sa.CheckConstraint('sequence_index >= 0', name='ck_transcript_segments_sequence_non_negative'),
    sa.CheckConstraint('start_time_ms >= 0', name='ck_transcript_segments_start_non_negative'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'sequence_index', name='uq_transcript_segments_meeting_sequence')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_transcript_segments_meeting_start', ['meeting_id', 'start_time_ms'], unique=False)
        batch_op.create_index('ix_transcript_segments_speaker_id', ['speaker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_transcript_segments_speaker_id')
        batch_op.drop_index('ix_transcript_segments_meeting_start')

    op.drop_table('transcript_segments')
    op.drop_table('topics')
    op.drop_table('summaries')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_meeting_participants_participant_meeting')

    op.drop_table('meeting_participants')
    op.drop_table('chapters')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index('ix_action_items_meeting_id')
        batch_op.drop_index('ix_action_items_assignee_id')

    op.drop_table('action_items')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index('ix_participants_name')

    op.drop_table('participants')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('ix_meetings_meeting_date')

    op.drop_table('meetings')
    # ### end Alembic commands ###
